name: Prepare container
description: Update host packages, configure OCO repo in xbps-src, run bootstrap-update
runs:
  using: composite
  steps:
    - name: Update host and configure xbps-src
      shell: sh
      run: |
        mkdir -p /var/db/xbps/keys
        if [ -f "${GITHUB_WORKSPACE}/extra/oco-repo-key.plist" ]; then
        	cp "${GITHUB_WORKSPACE}/extra/oco-repo-key.plist" \
            /var/db/xbps/keys/df:ec:10:ef:5c:03:e9:e0:9e:86:77:08:c2:b5:a8:cb.plist
        else
        	curl -fsSL "https://codeberg.org/oSoWoSo/oco/raw/branch/OCO/oco-repo-key.plist" \
        		-o /var/db/xbps/keys/df:ec:10:ef:5c:03:e9:e0:9e:86:77:08:c2:b5:a8:cb.plist || \
        	curl -fsSL "https://raw.githubusercontent.com/oSoWoSo/Void_Community_Repository/OCO/oco-repo-key.plist" \
        		-o /var/db/xbps/keys/df:ec:10:ef:5c:03:e9:e0:9e:86:77:08:c2:b5:a8:cb.plist
        fi

        echo y | xbps-install -S && return 0
        xbps-install -Syu xbps
        xbps-install -yu
        echo "XBPS_INSTALL_ARGS=\"-R https://repo.osowoso.org/${BOOTSTRAP}\"" >> /void-packages/etc/conf
        sudo -Eu builder sh -c "cd /void-packages && ./xbps-src bootstrap-update"
