#!/bin/sh
sv check dbus >/dev/null || exit 1
install -d -m0755 -o _cosmicgreeter -g _cosmicgreeter /run/cosmic-greeter
exec cosmic-greeter-daemon&
sleep 2s
exec greetd -c /etc/greetd/cosmic-greeter.toml
